### ISSUE TITLE
[CT-1793] [Feature] New GitHub Action to automate multiple formulae generation

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/homebrew-dbt#262]
### Describe the Feature

During the 12/2022 incident we had to manually regenerate every single formula for all adapters, all versions.  Every time we release new versions of dbt we also have to manually run a separate action for each adapter that was released.  Would be great if a single action could do this for us.

This should really be 2 actions.  
1.  Regenerate _all_ formulae and introspects the current formulae and regenerates them.  No inputs.
2. Generate one version per adapter
```
inputs:
  postgres:
    type: boolean
    default: false
  postgres_version:
    type: string
    description: "The package version to release"
     required: false
  postgres_is_default_version:
     description: "Is this version the latest stable release?"
     type: boolean
     required: false
  redshift:
    type: boolean
    default: false
  redshift_version:
    type: string
    description: "The package version to release"
     required: false
  redshift_is_default_version:
     description: "Is this version the latest stable release?"
     type: boolean
     required: false

...
```

It should validate that a valid version is provided if the adapter is marked for release.

Once validated it should just call `formula.yml` with the appropriate inputs.

Note: we don't release `dbt-spark` with Homebrew so do not include it here.
